version: '3.8'

services:
  react-app:
    image: apaluch/downloader-98:latest
    ports:
      - "3000:80"  # Expose React app on port 3000
    depends_on:
      - azurite
    networks:
      - react-network

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - "10000:10000"  # Blob service
      - "10001:10001"  # Queue service
      - "10002:10002"  # Table service
    environment:
      - AZURITE_CORS=*
    command: "azurite-blob --loose --blobHost 0.0.0.0 --location /data --debug /dev/stdout"
    volumes:
      - azurite_data:/data
    networks:
      - react-network
  
  gozurite:
    image: apaluch/gozurite:latest
    ports:
      - "8080:8080"
    networks:
      - react-network

volumes:
  azurite_data:

networks:
  react-network:
    driver: bridge